# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

#################################
#     HTTP for Reverse Proxy    #
#################################
#http:
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem
  #use_x_forwarded_for: true
  #trusted_proxies:
    #- 192.168.1.240
    #- 192.168.1.0/24

#########################
#     Input Booleans    #
#########################
input_boolean:
  livingroomtvpower:
    name: "Living Room TV"
    initial: off
  bathroom_light_turned_by_motion:
    name: "Bathroom Light"
    initial: off

#########################
#     Binary Sensors    #
#########################
binary_sensor:
  - platform: ping
    host: 192.168.1.226
    scan_interval: 20
    name: living_tv_status


#############################
#     Customize Switches    #
#############################
switch:
  - platform: template
    switches:
      bedroomrgb:
        turn_on:
          service: remote.send_command
          target:
            entity_id: remote.living_room
          data:
            command:
              - Power On
            device: 66670926
        turn_off:
          service: remote.send_command
          target:
            entity_id: remote.living_room
          data:
            command:
              - Power Off
            device: 66670926
  - platform: template
    switches:
      bathroomfan:
        turn_on:
          service: script.turn_on
          entity_id: script.bathroom_fan_full_on
        turn_off:
          service: light.turn_off
          entity_id: switch.bathroom_fan
  - platform: template
    switches:
      laundryroomfan:
        turn_on:
          service: script.turn_on
          entity_id: script.laundry_room_fan_on
        turn_off:
          service: light.turn_off
          entity_id: switch.laundry_fan


#################################
#     Home Assistant Config     #
#################################
homeassistant:
  auth_mfa_modules:
    - type: totp
#############################
#     Customize Entities    #
#############################
  customize:
    # Add an entry for each entity that you want to overwrite.
    ###################
    #     Kitchen     #
    ###################
    light.main_kitchen_light:
      friendly_name: Main Kitchen Light
      icon: mdi:dome-light
    light.1kitchen_cabinet_light:
      friendly_name: Kitchen Cabinet Light
      icon: mdi:led-strip-variant
    light.garbage_disposal:
      friendly_name: Garbage Disposal
      icon: mdi:delete-circle-outline
    #######################
    #     Dining Room     #
    #######################
    light.main_dining_room_light:
      friendly_name: Main Dining Room Light
      icon: mdi:track-light
    switch.occulus_light:
      friendly_name: Occulus Light
      icon: mdi:eye-outline
    #######################
    #     Living Room     #
    #######################
    media_player.living_room:
      friendly_name: Sonos Living Room
      icon: mdi:disc-player
    switch.living_room_tv_power:
        friendly_name: Living Room TV Power
        icon: mdi:television
    switch.living_room_watch_apple_tv:
      friendly_name: Watch Apple TV Living Room
      icon: mdi:youtube-tv
    light.main_living_room_lamp:
      friendly_name: Main Living Room Light
      icon: mdi:floor-lamp
    light.couch_light:
      friendly_name: Couch Light
      icon: mdi:lightbulb-outline
    light.couch_rgb:
      friendly_name: Couch RGB
      icon: mdi:lightbulb-on-outline
    light.tv_rgb:
      friendly_name: TV RGB
      icon: mdi:lightbulb-on-outline
    light.christmas_tree_light:
      friendly_name: Christmas Tree Light
      icon: mdi:pine-tree
    ###################
    #     Bedroom     #
    ###################
    switch.living_room_watch_fire_tv_bedroom:
      friendly_name: Watch Fire TV Bedroom
      icon: mdi:youtube-tv
    light.1joes_light:
      friendly_name: Joes Light
      icon: mdi:lightbulb-outline
    light.1shirleys_light:
      friendly_name: Shirleys Light
      icon: mdi:lightbulb-outline
    light.led_string_lights:
      friendly_name: LED String Lights
      icon: mdi:string-lights
    switch.bedroomrgb:
      friendly_name: Bedroom RGB
      icon: mdi:wall-sconce-flat-variant
    switch.bedroom_closet:
      friendly_name: Bedroom Closet Light
      icon: mdi:dome-light
    ########################
    #     Laundry Room     #
    ########################
    switch.laundry_fan:
      friendly_name: Laundry Fan
      icon: mdi:fan
    switch.laundryroomfan:
      friendly_name: 2 Hour Timer
      icon: mdi:fan-speed-2
    ####################
    #     Bathroom     #
    ####################
    light.bathroom_main_light:
      friendly_name: Main Bathroom Light
      icon: mdi:vanity-light
    switch.bathroom_fan:
      friendly_name: Bathroom Fan
      icon: mdi:emoticon-poop
    light.laundry_fan:
      friendly_name: Laundry Fan
      icon: mdi:fan
    ################
    #     Desk     #
    ################
    light.1desk_light:
      friendly_name: Desk Light
      icon: mdi:led-strip-variant
    switch.laptop:
      friendly_name: Laptop
      icon: mdi:laptop

#########################################
#     Lovelace Custom Config Modules    #
#########################################
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /local/state-switch.js
      type: module

#zwave:
#usb_path: /dev/zwave
#config_path: /config/ozwave/config

##########################
#     Google Calendar    #
##########################
google:
  client_id: !secret google_client_id_calendar
  client_secret: !secret google_client_secret_calendar

#########################
#     Included Files    #
#########################
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
